### ISSUE TITLE
Recent tokio changes?

### ISSUE THREAD

**Issue by denzp** [tokio-rs/tokio-compat#3]
Is it still possible to adjust the out-of-tree compatibility layer with the latest changes from tokio? I did a quick evaluation and it looks like much essential internals of tokio became private recently.

https://github.com/tokio-rs/tokio/commit/d70c928d88dff9e3e8d673b8ee02bce131598550
https://github.com/tokio-rs/tokio/commit/94f9b04b066cfc3da5c3ee2c961c21a9496135dd
https://github.com/tokio-rs/tokio/commit/69975fb9601bbb21659db283d888470733bae660
https://github.com/tokio-rs/tokio/commit/d5c1119c881c9a8b511aa9000fd26b9bda014256
https://github.com/tokio-rs/tokio/commit/27e5b41067d01c0c9fac230c5addb58034201a63

What is the current recommended approach of using v0.1 and v0.2 runtimes simultaneously?

**Comment by LucioFranco** [comment]
@denzp tokio should be shipping 0.2 today, once that is out we will pick up work again here. So expect some updates here shortly.

**Comment by hawkw** [comment]
Should have been closed by #6!
